server:
  port: ${config.serviceport:8787}
  servlet:
    context-path: /cecoapi
  tomcat:
    max-http-post-size: -1
    max-threads: 2000
    max-connections: 2000
    accept-count: 2500

spring:
  profiles:
    active: ${config.profile:dev}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

mybatis:
  basepackage: com.zf
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/**/*.xml"
# 项目相关配置
cekj:
  # 名称
  name: zflive
  # 版本
  version: 1.0.2
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  demoEnabled: true
  # 获取ip地址开关
  addressEnabled: true
url:
  ignore:
    startWith: "swagger,\
                loginByPwd,\
                getVerify"




